#!/usr/bin/env bash
#displays numbers from 1 to 20 where 4 9 and 17 displays bad luck from china, japan and italy respectively#
x=1
while (( x <= 20 ))
do
   echo "$x"
case $x in
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
esac
(( x++ ))
done
